cmake_minimum_required(VERSION 3.22)
project(BlockTraceRuleScanner VERSION 1.1 LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(glfw3 CONFIG REQUIRED)
find_package(imgui CONFIG REQUIRED)
find_package(OpenGL REQUIRED)
add_executable(BlockTraceRuleScanner WIN32 src/main.cpp src/gui/App.cpp src/gui/Theme.cpp src/gui/Starfield.cpp src/scanner/YaraRuleScanner.cpp)
target_include_directories(BlockTraceRuleScanner PRIVATE src)
target_link_libraries(BlockTraceRuleScanner PRIVATE glfw imgui::imgui OpenGL::GL comdlg32 dwmapi)
